#!/bin/sh

if [ ! -z "$2" ]; then
	ART_T="${2}"
else
	ART_T="00:00:10"
fi

FILENAME=$(basename -- "$1")
FILENAME="${FILENAME%.*}" #https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash

OFILE="$FILENAME".mka
OFILE_ART="$FILENAME".jpg

ffmpeg -i "$1" -vn -threads 1 -acodec copy "${OFILE}"
ffmpeg -i "$1" -ss "${ART_T}" -vframes 1 "${OFILE_ART}"
